create table if not exists public.monthly_payments (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  payment_month date not null,
  payment_date date null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint monthly_payments_month_start_check
    check (payment_month = date_trunc('month', payment_month)::date),
  constraint monthly_payments_customer_month_unique
    unique (customer_id, payment_month)
);

create index if not exists monthly_payments_customer_id_idx
on public.monthly_payments (customer_id);

create index if not exists monthly_payments_payment_month_idx
on public.monthly_payments (payment_month asc);

grant usage on schema public to authenticated;
grant select, insert, update, delete on table public.monthly_payments to authenticated;

alter table public.monthly_payments enable row level security;

drop policy if exists "Authenticated users can read monthly payments" on public.monthly_payments;
create policy "Authenticated users can read monthly payments"
on public.monthly_payments
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can insert monthly payments" on public.monthly_payments;
create policy "Authenticated users can insert monthly payments"
on public.monthly_payments
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update monthly payments" on public.monthly_payments;
create policy "Authenticated users can update monthly payments"
on public.monthly_payments
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can delete monthly payments" on public.monthly_payments;
create policy "Authenticated users can delete monthly payments"
on public.monthly_payments
for delete
to authenticated
using (true);

create or replace function public.touch_monthly_payments_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_monthly_payments_updated_at on public.monthly_payments;
create trigger set_monthly_payments_updated_at
before update on public.monthly_payments
for each row
execute function public.touch_monthly_payments_updated_at();
