-- RoundHQ tenant-safe schema for a fresh Supabase project.
--
-- Run this file in the Supabase SQL editor for the RoundHQ project.
-- Do not run the older Cleancut SQL files against the public SaaS database.

create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text null,
  owner_user_id uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists organizations_slug_unique_idx
on public.organizations (lower(slug))
where slug is not null;

create table if not exists public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text null,
  full_name text null,
  role text not null default 'owner' check (role in ('owner', 'admin', 'member')),
  status text not null default 'active' check (status in ('active', 'invited', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create index if not exists organization_members_user_id_idx
on public.organization_members (user_id);

create table if not exists public.subscriptions (
  organization_id uuid primary key references public.organizations(id) on delete cascade,
  stripe_customer_id text null,
  stripe_subscription_id text null,
  stripe_price_id text null,
  status text not null default 'trialing' check (
    status in (
      'incomplete',
      'incomplete_expired',
      'trialing',
      'active',
      'past_due',
      'canceled',
      'unpaid',
      'paused'
    )
  ),
  trial_ends_at timestamptz null default now() + interval '14 days',
  current_period_end timestamptz null,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.current_organization_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select organization_id
  from public.organization_members
  where user_id = auth.uid()
    and status = 'active'
  order by
    case role
      when 'owner' then 1
      when 'admin' then 2
      else 3
    end,
    created_at asc
  limit 1
$$;

create or replace function public.is_organization_member(target_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.organization_members
    where organization_id = target_organization_id
      and user_id = auth.uid()
      and status = 'active'
  )
$$;

create or replace function public.is_organization_admin(target_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.organization_members
    where organization_id = target_organization_id
      and user_id = auth.uid()
      and status = 'active'
      and role in ('owner', 'admin')
  )
$$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.app_state (
  organization_id uuid not null default public.current_organization_id()
    references public.organizations(id) on delete cascade,
  id text not null default 'primary',
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (organization_id, id)
);

create table if not exists public.staff_members (
  id bigint generated by default as identity primary key,
  organization_id uuid not null default public.current_organization_id()
    references public.organizations(id) on delete cascade,
  auth_user_id uuid null references auth.users(id) on delete set null,
  email text not null,
  full_name text not null,
  role text not null check (role in ('Admin', 'Staff', 'Operator')),
  is_active boolean not null default true,
  phone text null,
  notes text null,
  is_system_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists staff_members_org_email_unique_idx
on public.staff_members (organization_id, lower(email));

create unique index if not exists staff_members_org_auth_user_id_unique_idx
on public.staff_members (organization_id, auth_user_id)
where auth_user_id is not null;

create table if not exists public.role_permissions (
  organization_id uuid not null default public.current_organization_id()
    references public.organizations(id) on delete cascade,
  role text not null check (role in ('Admin', 'Staff', 'Operator')),
  page_key text not null check (
    page_key in (
      'dashboard',
      'schedule',
      'rounds',
      'history',
      'map',
      'actions',
      'commercial',
      'commercialDocs',
      'customers',
      'quotes',
      'invoices',
      'staff',
      'settings'
    )
  ),
  allowed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (organization_id, role, page_key)
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  organization_id uuid not null default public.current_organization_id()
    references public.organizations(id) on delete cascade,
  name text not null,
  address text not null,
  postcode text null,
  town text null,
  phone text null,
  email text null,
  contact_emails jsonb not null default '[]'::jsonb,
  is_grass_cutting_customer boolean not null default true,
  grass_cut_areas jsonb not null default '["All"]'::jsonb,
  week integer not null default 1 check (week in (1, 2)),
  day text null check (
    day is null or day in ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')
  ),
  customer_type text not null default 'Residential' check (
    customer_type in ('Residential', 'Commercial')
  ),
  cut_frequency text not null default 'Fortnightly' check (
    cut_frequency in ('Fortnightly', '3 Weekly', 'Monthly')
  ),
  site_name text null,
  site_address text null,
  site_town text null,
  site_postcode text null,
  payment_method text null check (
    payment_method is null or payment_method in ('Monthly', 'On Day Transfer', 'Cash')
  ),
  access_notes text null,
  notes text null,
  assigned_staff_id bigint null references public.staff_members(id) on delete set null,
  route_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  price numeric(10, 2) not null default 0,
  lat double precision null,
  lng double precision null,
  check (jsonb_typeof(contact_emails) = 'array'),
  check (jsonb_typeof(grass_cut_areas) = 'array')
);

create index if not exists customers_org_name_idx
on public.customers (organization_id, name);

create index if not exists customers_org_round_idx
on public.customers (organization_id, week, day, customer_type, route_order);

create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  organization_id uuid not null default public.current_organization_id()
    references public.organizations(id) on delete cascade,
  customer_id bigint not null references public.customers(id) on delete cascade,
  visit_date date not null,
  week integer null check (week is null or week in (1, 2)),
  day text null check (
    day is null or day in ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')
  ),
  status text not null check (status in ('completed', 'not_cut')),
  notes text null,
  payment_status text not null default 'Not Paid' check (payment_status in ('Paid', 'Not Paid')),
  paid_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reason text null check (
    reason is null or reason in (
      'Too Wet',
      'Access Blocked',
      'Customer Request',
      'Overgrown - Requires Quote',
      'Unsafe',
      'Dog in Garden',
      'Gate Locked',
      'Other'
    )
  ),
  round_key text null,
  customer_type text null check (
    customer_type is null or customer_type in ('Residential', 'Commercial')
  ),
  price_at_visit numeric(10, 2) null
);

create index if not exists visits_org_date_idx
on public.visits (organization_id, visit_date desc);

create index if not exists visits_org_customer_idx
on public.visits (organization_id, customer_id);

create index if not exists visits_org_round_key_idx
on public.visits (organization_id, round_key);

create table if not exists public.customer_leads (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null default public.current_organization_id()
    references public.organizations(id) on delete cascade,
  source text not null default 'website' check (
    source in ('website', 'email', 'facebook', 'whatsapp', 'manual')
  ),
  status text not null default 'new' check (
    status in ('new', 'reviewing', 'replied', 'converted', 'archived')
  ),
  name text null,
  email text null,
  phone text null,
  address text null,
  town text null,
  postcode text null,
  customer_type text null check (
    customer_type is null or customer_type in ('Residential', 'Commercial')
  ),
  service text null,
  preferred_contact text null check (
    preferred_contact is null or preferred_contact in ('email', 'text', 'phone')
  ),
  message text not null default '',
  notes text null,
  extracted_data jsonb not null default '{}'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  reply_history jsonb not null default '[]'::jsonb,
  activity_history jsonb not null default '[]'::jsonb,
  submitted_at timestamptz not null default now(),
  converted_customer_id bigint null references public.customers(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(extracted_data) = 'object'),
  check (jsonb_typeof(raw_payload) = 'object'),
  check (jsonb_typeof(reply_history) = 'array'),
  check (jsonb_typeof(activity_history) = 'array')
);

create index if not exists customer_leads_org_status_idx
on public.customer_leads (organization_id, status);

create index if not exists customer_leads_org_submitted_at_idx
on public.customer_leads (organization_id, submitted_at desc);

create table if not exists public.monthly_payments (
  id bigint generated by default as identity primary key,
  organization_id uuid not null default public.current_organization_id()
    references public.organizations(id) on delete cascade,
  customer_id bigint not null references public.customers(id) on delete cascade,
  payment_month date not null,
  payment_date date null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint monthly_payments_month_start_check
    check (payment_month = date_trunc('month', payment_month)::date),
  constraint monthly_payments_customer_month_unique
    unique (customer_id, payment_month)
);

create index if not exists monthly_payments_org_month_idx
on public.monthly_payments (organization_id, payment_month asc);

create table if not exists public.items (
  id text primary key,
  organization_id uuid not null default public.current_organization_id()
    references public.organizations(id) on delete cascade,
  title text not null,
  category text null,
  item_type text not null check (item_type in ('service', 'product')),
  price numeric(12, 2) not null default 0,
  buy_price numeric(12, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists items_org_unique_catalog_idx
on public.items (organization_id, lower(title), lower(coalesce(category, '')), item_type);

create index if not exists items_org_category_idx
on public.items (organization_id, category);

create table if not exists public.quotes (
  id text primary key,
  organization_id uuid not null default public.current_organization_id()
    references public.organizations(id) on delete cascade,
  quote_number text not null,
  customer_id bigint null references public.customers(id) on delete set null,
  customer_name text not null,
  customer_type text null,
  customer_address text null,
  customer_town text null,
  customer_postcode text null,
  site_name text null,
  site_address text null,
  site_town text null,
  site_postcode text null,
  date date not null,
  status text not null check (
    status in ('Draft', 'Approved', 'Sent', 'Accepted', 'Scheduled', 'Declined', 'Rejected')
  ),
  items jsonb not null default '[]'::jsonb,
  notes text null,
  total numeric(12, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(items) = 'array')
);

create unique index if not exists quotes_org_quote_number_unique_idx
on public.quotes (organization_id, quote_number);

create index if not exists quotes_org_date_idx
on public.quotes (organization_id, date desc);

create table if not exists public.invoices (
  id text primary key,
  organization_id uuid not null default public.current_organization_id()
    references public.organizations(id) on delete cascade,
  invoice_number text not null,
  customer_id bigint null references public.customers(id) on delete set null,
  customer_name text not null,
  customer_type text null,
  customer_address text null,
  customer_town text null,
  customer_postcode text null,
  site_name text null,
  site_address text null,
  site_town text null,
  site_postcode text null,
  date date not null,
  due_date date null,
  status text not null check (
    status in ('Draft', 'Approved', 'Sent', 'Accepted', 'Declined', 'Unpaid', 'Paid')
  ),
  items jsonb not null default '[]'::jsonb,
  notes text null,
  terms text null,
  vat_rate numeric(5, 2) null,
  vat_amount numeric(12, 2) null,
  total numeric(12, 2) not null default 0,
  linked_quote_id text null references public.quotes(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(items) = 'array')
);

create unique index if not exists invoices_org_invoice_number_unique_idx
on public.invoices (organization_id, invoice_number);

create index if not exists invoices_org_date_idx
on public.invoices (organization_id, date desc);

create table if not exists public.recurring_invoice_templates (
  id text primary key,
  organization_id uuid not null default public.current_organization_id()
    references public.organizations(id) on delete cascade,
  source_invoice_id text null references public.invoices(id) on delete set null,
  customer_id bigint null references public.customers(id) on delete set null,
  customer_name text not null,
  customer_type text null,
  customer_address text null,
  customer_town text null,
  customer_postcode text null,
  site_name text null,
  site_address text null,
  site_town text null,
  site_postcode text null,
  status text not null check (
    status in ('Draft', 'Approved', 'Sent', 'Accepted', 'Declined', 'Unpaid', 'Paid')
  ),
  items jsonb not null default '[]'::jsonb,
  notes text null,
  terms text null,
  vat_rate numeric(5, 2) null,
  due_days_after_issue integer null check (due_days_after_issue is null or due_days_after_issue >= 0),
  linked_quote_id text null references public.quotes(id) on delete set null,
  frequency text not null check (frequency in ('Monthly', 'Quarterly', 'Yearly')),
  next_send_date date not null,
  preferred_send_method text null check (preferred_send_method is null or preferred_send_method in ('email', 'text')),
  send_to text null,
  is_active boolean not null default true,
  last_generated_date date null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(items) = 'array')
);

create index if not exists recurring_invoice_templates_org_next_send_date_idx
on public.recurring_invoice_templates (organization_id, next_send_date asc);

create table if not exists public.scheduled_jobs (
  id text primary key,
  organization_id uuid not null default public.current_organization_id()
    references public.organizations(id) on delete cascade,
  title text not null,
  date date not null,
  notes text null,
  start_time time null,
  finish_time time null,
  customer_id bigint null references public.customers(id) on delete set null,
  customer_name text null,
  type text not null check (type in ('One Off', 'Quote Accepted', 'Grass Cut', 'Commercial')),
  status text not null check (status in ('Scheduled', 'In Progress', 'Completed', 'Cancelled')),
  quote_ids jsonb not null default '[]'::jsonb,
  invoice_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(quote_ids) = 'array'),
  check (jsonb_typeof(invoice_ids) = 'array')
);

create index if not exists scheduled_jobs_org_date_idx
on public.scheduled_jobs (organization_id, date asc);

create table if not exists public.commercial_rams_documents (
  id text primary key,
  organization_id uuid not null default public.current_organization_id()
    references public.organizations(id) on delete cascade,
  customer_id bigint null references public.customers(id) on delete set null,
  customer_name text not null,
  customer_address text null,
  customer_town text null,
  customer_postcode text null,
  site_name text null,
  site_address text null,
  site_town text null,
  site_postcode text null,
  job_title text null,
  reference_number text null,
  revision text null,
  start_date date null,
  estimated_duration text null,
  prepared_by text null,
  work_type text not null check (
    work_type in (
      'Grass Cutting',
      'Hedge Cutting',
      'Pressure Washing',
      'Gutter Cleaning',
      'Grounds Maintenance',
      'Other'
    )
  ),
  operatives text null,
  site_supervisor text null,
  emergency_contact text null,
  custom_scope text null,
  public_access text not null check (public_access in ('Yes', 'No')),
  public_access_notes text null,
  working_at_height text not null check (working_at_height in ('Yes', 'No')),
  working_at_height_notes text null,
  chemicals text not null check (chemicals in ('Yes', 'No')),
  chemicals_notes text null,
  vehicle_movement text not null check (vehicle_movement in ('Yes', 'No')),
  vehicle_movement_notes text null,
  powered_machinery text not null check (powered_machinery in ('Yes', 'No')),
  powered_machinery_notes text null,
  services text not null check (services in ('Yes', 'No')),
  services_notes text null,
  method_notes text null,
  additional_hazards text null,
  site_contact text null,
  site_contact_number text null,
  nearest_hospital text null,
  emergency_procedure text null,
  client_approval_name text null,
  approval_role text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists commercial_rams_org_updated_at_idx
on public.commercial_rams_documents (organization_id, updated_at desc);

create or replace function public.seed_roundhq_organization(target_organization_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.app_state (organization_id, id, data)
  values (target_organization_id, 'primary', '{}'::jsonb)
  on conflict (organization_id, id) do nothing;

  insert into public.subscriptions (organization_id, status)
  values (target_organization_id, 'trialing')
  on conflict (organization_id) do nothing;

  insert into public.role_permissions (organization_id, role, page_key, allowed)
  values
    (target_organization_id, 'Admin', 'dashboard', true),
    (target_organization_id, 'Admin', 'schedule', true),
    (target_organization_id, 'Admin', 'rounds', true),
    (target_organization_id, 'Admin', 'history', true),
    (target_organization_id, 'Admin', 'map', true),
    (target_organization_id, 'Admin', 'actions', true),
    (target_organization_id, 'Admin', 'commercial', true),
    (target_organization_id, 'Admin', 'commercialDocs', true),
    (target_organization_id, 'Admin', 'customers', true),
    (target_organization_id, 'Admin', 'quotes', true),
    (target_organization_id, 'Admin', 'invoices', true),
    (target_organization_id, 'Admin', 'staff', true),
    (target_organization_id, 'Admin', 'settings', true),
    (target_organization_id, 'Staff', 'dashboard', true),
    (target_organization_id, 'Staff', 'schedule', true),
    (target_organization_id, 'Staff', 'rounds', true),
    (target_organization_id, 'Staff', 'history', true),
    (target_organization_id, 'Staff', 'map', true),
    (target_organization_id, 'Staff', 'actions', true),
    (target_organization_id, 'Staff', 'commercial', true),
    (target_organization_id, 'Staff', 'commercialDocs', true),
    (target_organization_id, 'Staff', 'customers', true),
    (target_organization_id, 'Staff', 'quotes', true),
    (target_organization_id, 'Staff', 'invoices', true),
    (target_organization_id, 'Staff', 'staff', false),
    (target_organization_id, 'Staff', 'settings', false),
    (target_organization_id, 'Operator', 'dashboard', true),
    (target_organization_id, 'Operator', 'schedule', false),
    (target_organization_id, 'Operator', 'rounds', true),
    (target_organization_id, 'Operator', 'history', true),
    (target_organization_id, 'Operator', 'map', true),
    (target_organization_id, 'Operator', 'actions', true),
    (target_organization_id, 'Operator', 'commercial', true),
    (target_organization_id, 'Operator', 'commercialDocs', false),
    (target_organization_id, 'Operator', 'customers', false),
    (target_organization_id, 'Operator', 'quotes', false),
    (target_organization_id, 'Operator', 'invoices', false),
    (target_organization_id, 'Operator', 'staff', false),
    (target_organization_id, 'Operator', 'settings', false)
  on conflict (organization_id, role, page_key) do nothing;
end;
$$;

create or replace function public.handle_roundhq_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  new_organization_id uuid;
  new_company_name text;
  new_full_name text;
begin
  new_company_name := nullif(btrim(coalesce(new.raw_user_meta_data ->> 'company_name', '')), '');
  new_full_name := nullif(btrim(coalesce(new.raw_user_meta_data ->> 'full_name', '')), '');

  if new_company_name is null then
    new_company_name := coalesce(nullif(split_part(new.email, '@', 1), ''), 'RoundHQ Workspace');
  end if;

  insert into public.organizations (name, owner_user_id)
  values (new_company_name, new.id)
  returning id into new_organization_id;

  insert into public.organization_members (
    organization_id,
    user_id,
    email,
    full_name,
    role,
    status
  )
  values (
    new_organization_id,
    new.id,
    new.email,
    coalesce(new_full_name, new.email),
    'owner',
    'active'
  );

  insert into public.staff_members (
    organization_id,
    auth_user_id,
    email,
    full_name,
    role,
    is_active,
    is_system_admin
  )
  values (
    new_organization_id,
    new.id,
    coalesce(new.email, ''),
    coalesce(new_full_name, new.email, 'Owner'),
    'Admin',
    true,
    true
  );

  perform public.seed_roundhq_organization(new_organization_id);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_roundhq on auth.users;
create trigger on_auth_user_created_roundhq
after insert on auth.users
for each row
execute function public.handle_roundhq_new_user();

do $$
declare
  existing_user record;
  new_organization_id uuid;
  new_company_name text;
  new_full_name text;
begin
  for existing_user in
    select auth_user.id, auth_user.email, auth_user.raw_user_meta_data
    from auth.users as auth_user
    where not exists (
      select 1
      from public.organization_members
      where user_id = auth_user.id
    )
  loop
    new_company_name := nullif(btrim(coalesce(existing_user.raw_user_meta_data ->> 'company_name', '')), '');
    new_full_name := nullif(btrim(coalesce(existing_user.raw_user_meta_data ->> 'full_name', '')), '');

    if new_company_name is null then
      new_company_name := coalesce(nullif(split_part(existing_user.email, '@', 1), ''), 'RoundHQ Workspace');
    end if;

    insert into public.organizations (name, owner_user_id)
    values (new_company_name, existing_user.id)
    returning id into new_organization_id;

    insert into public.organization_members (
      organization_id,
      user_id,
      email,
      full_name,
      role,
      status
    )
    values (
      new_organization_id,
      existing_user.id,
      existing_user.email,
      coalesce(new_full_name, existing_user.email),
      'owner',
      'active'
    );

    insert into public.staff_members (
      organization_id,
      auth_user_id,
      email,
      full_name,
      role,
      is_active,
      is_system_admin
    )
    values (
      new_organization_id,
      existing_user.id,
      coalesce(existing_user.email, ''),
      coalesce(new_full_name, existing_user.email, 'Owner'),
      'Admin',
      true,
      true
    );

    perform public.seed_roundhq_organization(new_organization_id);
  end loop;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'organizations',
    'organization_members',
    'subscriptions',
    'staff_members',
    'role_permissions',
    'customers',
    'visits',
    'customer_leads',
    'monthly_payments',
    'items',
    'quotes',
    'invoices',
    'recurring_invoice_templates',
    'scheduled_jobs',
    'commercial_rams_documents'
  ]
  loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', table_name, table_name);
    execute format(
      'create trigger set_%I_updated_at before update on public.%I for each row execute function public.touch_updated_at()',
      table_name,
      table_name
    );
  end loop;
end;
$$;

grant usage on schema public to anon, authenticated;
grant execute on function public.current_organization_id() to authenticated;
grant execute on function public.is_organization_member(uuid) to authenticated;
grant execute on function public.is_organization_admin(uuid) to authenticated;
revoke execute on function public.seed_roundhq_organization(uuid) from public, anon, authenticated;
revoke execute on function public.handle_roundhq_new_user() from public, anon, authenticated;

grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.subscriptions enable row level security;
alter table public.app_state enable row level security;
alter table public.staff_members enable row level security;
alter table public.role_permissions enable row level security;
alter table public.customers enable row level security;
alter table public.visits enable row level security;
alter table public.customer_leads enable row level security;
alter table public.monthly_payments enable row level security;
alter table public.items enable row level security;
alter table public.quotes enable row level security;
alter table public.invoices enable row level security;
alter table public.recurring_invoice_templates enable row level security;
alter table public.scheduled_jobs enable row level security;
alter table public.commercial_rams_documents enable row level security;

drop policy if exists "Members can read organizations" on public.organizations;
create policy "Members can read organizations"
on public.organizations
for select
to authenticated
using (public.is_organization_member(id));

drop policy if exists "Admins can update organizations" on public.organizations;
create policy "Admins can update organizations"
on public.organizations
for update
to authenticated
using (public.is_organization_admin(id))
with check (public.is_organization_admin(id));

drop policy if exists "Members can read organization members" on public.organization_members;
create policy "Members can read organization members"
on public.organization_members
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Admins can manage organization members" on public.organization_members;
create policy "Admins can manage organization members"
on public.organization_members
for all
to authenticated
using (public.is_organization_admin(organization_id))
with check (public.is_organization_admin(organization_id));

drop policy if exists "Members can read subscriptions" on public.subscriptions;
create policy "Members can read subscriptions"
on public.subscriptions
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Admins can update subscriptions" on public.subscriptions;
create policy "Admins can update subscriptions"
on public.subscriptions
for update
to authenticated
using (public.is_organization_admin(organization_id))
with check (public.is_organization_admin(organization_id));

drop policy if exists "Members can read app state" on public.app_state;
create policy "Members can read app state"
on public.app_state
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Members can write app state" on public.app_state;
create policy "Members can write app state"
on public.app_state
for all
to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));

drop policy if exists "Members can read staff members" on public.staff_members;
create policy "Members can read staff members"
on public.staff_members
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Admins can write staff members" on public.staff_members;
create policy "Admins can write staff members"
on public.staff_members
for all
to authenticated
using (public.is_organization_admin(organization_id))
with check (public.is_organization_admin(organization_id));

drop policy if exists "Members can read role permissions" on public.role_permissions;
create policy "Members can read role permissions"
on public.role_permissions
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Admins can write role permissions" on public.role_permissions;
create policy "Admins can write role permissions"
on public.role_permissions
for all
to authenticated
using (public.is_organization_admin(organization_id))
with check (public.is_organization_admin(organization_id));

drop policy if exists "Members can read customers" on public.customers;
create policy "Members can read customers"
on public.customers
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Members can write customers" on public.customers;
create policy "Members can write customers"
on public.customers
for all
to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));

drop policy if exists "Members can read visits" on public.visits;
create policy "Members can read visits"
on public.visits
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Members can write visits" on public.visits;
create policy "Members can write visits"
on public.visits
for all
to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));

drop policy if exists "Members can read customer leads" on public.customer_leads;
create policy "Members can read customer leads"
on public.customer_leads
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Members can write customer leads" on public.customer_leads;
create policy "Members can write customer leads"
on public.customer_leads
for all
to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));

drop policy if exists "Members can read monthly payments" on public.monthly_payments;
create policy "Members can read monthly payments"
on public.monthly_payments
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Members can write monthly payments" on public.monthly_payments;
create policy "Members can write monthly payments"
on public.monthly_payments
for all
to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));

drop policy if exists "Members can read items" on public.items;
create policy "Members can read items"
on public.items
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Members can write items" on public.items;
create policy "Members can write items"
on public.items
for all
to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));

drop policy if exists "Members can read quotes" on public.quotes;
create policy "Members can read quotes"
on public.quotes
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Members can write quotes" on public.quotes;
create policy "Members can write quotes"
on public.quotes
for all
to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));

drop policy if exists "Members can read invoices" on public.invoices;
create policy "Members can read invoices"
on public.invoices
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Members can write invoices" on public.invoices;
create policy "Members can write invoices"
on public.invoices
for all
to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));

drop policy if exists "Members can read recurring invoice templates" on public.recurring_invoice_templates;
create policy "Members can read recurring invoice templates"
on public.recurring_invoice_templates
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Members can write recurring invoice templates" on public.recurring_invoice_templates;
create policy "Members can write recurring invoice templates"
on public.recurring_invoice_templates
for all
to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));

drop policy if exists "Members can read scheduled jobs" on public.scheduled_jobs;
create policy "Members can read scheduled jobs"
on public.scheduled_jobs
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Members can write scheduled jobs" on public.scheduled_jobs;
create policy "Members can write scheduled jobs"
on public.scheduled_jobs
for all
to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));

drop policy if exists "Members can read commercial RAMS" on public.commercial_rams_documents;
create policy "Members can read commercial RAMS"
on public.commercial_rams_documents
for select
to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Members can write commercial RAMS" on public.commercial_rams_documents;
create policy "Members can write commercial RAMS"
on public.commercial_rams_documents
for all
to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
