create table if not exists public.staff_members (
  id bigint generated by default as identity primary key,
  auth_user_id uuid null,
  email text not null,
  full_name text not null,
  role text not null check (role in ('Admin', 'Manager', 'Staff', 'Operator')),
  is_active boolean not null default true,
  phone text null,
  notes text null,
  is_system_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists staff_members_email_unique_idx
on public.staff_members (lower(email));

create unique index if not exists staff_members_auth_user_id_unique_idx
on public.staff_members (auth_user_id)
where auth_user_id is not null;

create unique index if not exists staff_members_single_system_admin_idx
on public.staff_members (is_system_admin)
where is_system_admin = true;

create table if not exists public.role_permissions (
  role text not null check (role in ('Admin', 'Manager', 'Staff', 'Operator')),
  page_key text not null check (
    page_key in (
      'technician',
      'dashboard',
      'schedule',
      'rounds',
      'history',
      'map',
      'actions',
      'commercial',
      'commercialDocs',
      'customers',
      'expenses',
      'quotes',
      'invoices',
      'staff',
      'settings'
    )
  ),
  allowed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (role, page_key)
);

alter table public.role_permissions
drop constraint if exists role_permissions_page_key_check;

alter table public.staff_members
drop constraint if exists staff_members_role_check;

alter table public.staff_members
add constraint staff_members_role_check
check (role in ('Admin', 'Manager', 'Staff', 'Operator'));

alter table public.role_permissions
drop constraint if exists role_permissions_role_check;

alter table public.role_permissions
add constraint role_permissions_role_check
check (role in ('Admin', 'Manager', 'Staff', 'Operator'));

alter table public.role_permissions
add constraint role_permissions_page_key_check
check (
  page_key in (
    'technician',
    'dashboard',
    'schedule',
    'rounds',
    'history',
    'map',
    'actions',
    'commercial',
    'commercialDocs',
    'customers',
    'expenses',
    'quotes',
    'invoices',
    'staff',
    'settings'
  )
);

insert into public.role_permissions (role, page_key, allowed)
values
  ('Admin', 'technician', true),
  ('Admin', 'dashboard', true),
  ('Admin', 'schedule', true),
  ('Admin', 'rounds', true),
  ('Admin', 'history', true),
  ('Admin', 'map', true),
  ('Admin', 'actions', true),
  ('Admin', 'commercial', true),
  ('Admin', 'commercialDocs', true),
  ('Admin', 'customers', true),
  ('Admin', 'expenses', true),
  ('Admin', 'quotes', true),
  ('Admin', 'invoices', true),
  ('Admin', 'staff', true),
  ('Admin', 'settings', true),
  ('Manager', 'technician', true),
  ('Manager', 'dashboard', true),
  ('Manager', 'schedule', true),
  ('Manager', 'rounds', true),
  ('Manager', 'history', true),
  ('Manager', 'map', true),
  ('Manager', 'actions', true),
  ('Manager', 'commercial', true),
  ('Manager', 'commercialDocs', true),
  ('Manager', 'customers', true),
  ('Manager', 'expenses', true),
  ('Manager', 'quotes', true),
  ('Manager', 'invoices', true),
  ('Manager', 'staff', false),
  ('Manager', 'settings', false),
  ('Staff', 'technician', true),
  ('Staff', 'dashboard', false),
  ('Staff', 'schedule', false),
  ('Staff', 'rounds', false),
  ('Staff', 'history', false),
  ('Staff', 'map', false),
  ('Staff', 'actions', false),
  ('Staff', 'commercial', false),
  ('Staff', 'commercialDocs', false),
  ('Staff', 'customers', false),
  ('Staff', 'expenses', false),
  ('Staff', 'quotes', false),
  ('Staff', 'invoices', false),
  ('Staff', 'staff', false),
  ('Staff', 'settings', false)
on conflict (role, page_key) do nothing;

alter table public.staff_members enable row level security;
alter table public.role_permissions enable row level security;

drop policy if exists "Authenticated users can read staff members" on public.staff_members;
create policy "Authenticated users can read staff members"
on public.staff_members
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can insert staff members" on public.staff_members;
create policy "Authenticated users can insert staff members"
on public.staff_members
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update staff members" on public.staff_members;
create policy "Authenticated users can update staff members"
on public.staff_members
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can delete staff members" on public.staff_members;
create policy "Authenticated users can delete staff members"
on public.staff_members
for delete
to authenticated
using (true);

drop policy if exists "Authenticated users can read role permissions" on public.role_permissions;
create policy "Authenticated users can read role permissions"
on public.role_permissions
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can insert role permissions" on public.role_permissions;
create policy "Authenticated users can insert role permissions"
on public.role_permissions
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update role permissions" on public.role_permissions;
create policy "Authenticated users can update role permissions"
on public.role_permissions
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can delete role permissions" on public.role_permissions;
create policy "Authenticated users can delete role permissions"
on public.role_permissions
for delete
to authenticated
using (true);

create or replace function public.touch_workflow_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_staff_members_updated_at on public.staff_members;
create trigger set_staff_members_updated_at
before update on public.staff_members
for each row
execute function public.touch_workflow_updated_at();

drop trigger if exists set_role_permissions_updated_at on public.role_permissions;
create trigger set_role_permissions_updated_at
before update on public.role_permissions
for each row
execute function public.touch_workflow_updated_at();
